### ISSUE TITLE
guidelines for organization of this repo?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/stancon2023#2]
Folder names are almost all speaker name First-Last.

We need a little cleanup w/r/t folder Boumis-Tsunami and 2 copies of pdf.

Repo also needs a README.md file

**Comment by bob-carpenter** [comment]
@mitzimorris:  Are you going to fix this or should I?

**Comment by mitzimorris** [comment]
fixed.

**Comment by mitzimorris** [comment]
only fixed folder names.  working on README

**Comment by mitzimorris** [comment]
added README and markdown of talks and tutorials (copied from announcement on stan-dev.github.io)
